name: MacOS make

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: dependencies
      run: brew install pkgconfig jack coreutils
    - name: cloneresampler
      run: git clone https://github.com/gisogrimm/zita-resampler.git
    - name: resampler
      run: make -C zita-resampler/source libzita-resampler.a
    - name: njbridge
      run: make -C source CXXFLAGS+="$(pkg-config --cflags jack) -I../zita-resampler/source" LDFLAGS+="$(pkg-config --libs jack) -L../zita-resampler/source" -f Makefile-osx
