name: Ubuntu make

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: dependencies
      run: apt update &&
           apt install --assume-yes git 
    - name: resampler
      run: make -C zita-resampler/source libzita-resampler.a
    - name: njbridge
      run: make -C source CXXFLAGS+="$(shell pkg-config --cflags jack) -I../zita-resampler/source" LDFLAGS+="$(shell pkg-config --libs jack) -L../zita-resampler/source" -f Makefile-linux
